branch-defaults:
  development:
    environment: null
global:
  application_name: welunch
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: eu-west-1
  profile: eb-cli
  sc: git
